language: c++
dist: trusty
sudo: true

script:
  - sudo apt-get -y install libqt4-dev qt4-qmake lintian
  - ( cd firetools ; ./configure --enable-fatal-warnings --prefix=/usr && make && sudo make install && make deb)
